name = "bse-rss-backend"
main = "index.js"
compatibility_date = "2026-01-01"

[triggers]
crons = [
  "0-59/1 0-12 * * *",
  "0-59/10 13-23 * * *"
]

[[kv_namespaces]]
binding = "BSE_STORE"
id = "c1a132db8e7e41f0a54ff4841cf6d143"